### ISSUE TITLE
eckit 1.10 breaks fckit on s4

### ISSUE THREAD

**Issue by markjolah** [JCSDA/fckit#23]
With the new `eckit/jcsda-1.10.1.jcsda1` module on s4, I cannot build fckit.
```
/home/molah/.jedi-rapids/build/bundle/master/fckit/src/fckit/module/fckit_mpi.cc(387): error: class "eckit::mpi::Comm" has no member "infoNull"
          return comm->infoNull();
                       ^

/home/molah/.jedi-rapids/build/bundle/master/fckit/src/fckit/module/fckit_mpi.cc(389): error: class "eckit::mpi::Comm" has no member "infoNull"
          return eckit::mpi::comm().infoNull();
                                    ^

compilation aborted for /home/molah/.jedi-rapids/build/bundle/master/fckit/src/fckit/module/fckit_mpi.cc (code 2)
make[2]: *** [fckit/src/fckit/CMakeFiles/fckit.dir/module/fckit_mpi.cc.o] Error 2
make[1]: *** [fckit/src/fckit/CMakeFiles/fckit.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by mmiesch** [comment]
You need the `feature/towards_sync_with_ecmwf` branch of fckit.  For that reason, my intention was to use the old eckit in the `jedi/intel19-impi` module but that was getting re-loaded by odc - I was in the process of fixing that but S4 just froze up

**Comment by mmiesch** [comment]
Ok - fixed - the `jedi/intel19-impi` module should be the same as before.  To use the new versions of ecbuild, eckit, and odc you can load `jedi/intel19-beta`, but this requires the `feature/towards_sync_with_ecmwf` branch of fckit.  When fckit development settles down a bit, we can tag it and I can make that beta module the default. I just want to wait a few days for fckit.

**Comment by markjolah** [comment]
Great thanks Mark for the fast reply!  I will test it out ant let you know.  See my email for further discussion.
